teams:
  - name: olahsymbo
    permission: admin

repository:
  name: object-detection-yolov5
  description: Object Detection using Yolov5 and FastAPI
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        require_code_owner_reviews: true
